import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  tutorialSidebar: [
    "intro",
    {
      type: "category",
      label: "Getting Started",
      items: ["getting-started/installation", "getting-started/first-steps"],
    },
    {
      type: "category",
      label: "Projects",
      items: [
        "projects/creating-a-new-project",
        "projects/working-on-an-existing-project",
        "projects/dependencies",
        "projects/project-layout",
      ],
    },
    {
      type: "category",
      label: "Spark Overview",
      items: [
        "spark/overview-spark",
        {
          type: "category",
          label: "Tests",
          link: {
            type: "doc",

            id: "spark/tests",
          },

          items: [
            "spark/writing-tests",
            "spark/cheatcodes",
            "spark/spark-std",
            "spark/traces",
            "spark/fork-testing",
          ],
        },
        {
          type: "category",
          label: "Advanced Testing",
          link: {
            type: "doc",

            id: "spark/advanced-testing",
          },

          items: [
            "spark/fuzz-testing",
            "spark/invariant-testing",
            "spark/differential-ffi-testing",
          ],
        },
        "spark/deploying",
        {
          type: "category",
          label: "Gas Tracking",
          link: {
            type: "doc",

            id: "spark/gas-tracking",
          },

          items: ["spark/gas-reports", "spark/gas-snapshots"],
        },
        "spark/debugger",
      ],
    },
    {
      type: "category",
      label: "Probe Overview",
      items: ["probe/probe-overview"],
    },
    {
      type: "category",
      label: "Shuttle Overview",
      items: ["shuttle/shuttle-overview"],
    },
    {
      type: "category",
      label: "Pilot Overview",
      items: ["pilot/pilot-overview"],
    },
    {
      type: "category",
      label: "Configuration",
      items: [
        "config/configuration",
        "config/continuous-integration",
        "config/vscode",
        "config/shell-autocompletion",
        "config/static-analyzers",
        "config/hardhat",
      ],
    },
    {
      type: "category",
      label: "Tutorials",
      items: [
        "tutorials/best-practices",
        "tutorials/solmate-nft",
        "tutorials/foxar-docker",
        "tutorials/testing-eip712",
        "tutorials/solidity-scripting",
        "tutorials/create2-tutorial",
        "tutorials/forking-mainnet-with-probe-shuttle",
        "tutorials/learn-foxar",
      ],
    },
    {
      type: "category",
      label: "Appendix",
      items: [
        "faq",
        "contributing",

        {
          type: "category",
          label: "References",
          link: {
            type: "doc",

            id: "reference/reference",
          },
          items: [
            {
              type: "category",
              label: "CLI Reference",
              link: {
                type: "doc",

                id: "reference/cli/cli-reference",
              },
              items: [
                {
                  type: "category",
                  label: "spark",
                  link: {
                    type: "doc",

                    id: "reference/cli/spark",
                  },
                  items: [
                    "reference/cli/spark/bind",
                    "reference/cli/spark/build",
                    {
                      type: "category",
                      label: "spark cache",
                      link: {
                        type: "doc",

                        id: "reference/cli/spark/cache",
                      },
                      items: [
                        "reference/cli/spark/cache/clean",
                        "reference/cli/spark/cache/ls",
                      ],
                    },
                    "reference/cli/spark/clean",
                    "reference/cli/spark/completions",
                    "reference/cli/spark/config",
                    "reference/cli/spark/coverage",
                    "reference/cli/spark/create",
                    "reference/cli/spark/debug",
                    "reference/cli/spark/doc",
                    "reference/cli/spark/flatten",
                    "reference/cli/spark/fmt",
                    "reference/cli/spark/geiger",
                    {
                      type: "category",
                      label: "spark generate",
                      link: {
                        type: "doc",

                        id: "reference/cli/spark/generate",
                      },
                      items: ["reference/cli/spark/generate/test"],
                    },
                    "reference/cli/spark/generate-fig-spec",
                    "reference/cli/spark/init",
                    "reference/cli/spark/inspect",
                    "reference/cli/spark/install",
                    "reference/cli/spark/remappings",
                    "reference/cli/spark/remove",
                    "reference/cli/spark/script",
                    {
                      type: "category",
                      label: "spark selectors",
                      link: {
                        type: "doc",

                        id: "reference/cli/spark/selectors",
                      },
                      items: [
                        "reference/cli/spark/selectors/collision",
                        "reference/cli/spark/selectors/upload",
                        "reference/cli/spark/selectors/list",
                      ],
                    },
                    "reference/cli/spark/snapshot",
                    "reference/cli/spark/test",
                    "reference/cli/spark/tree",
                    "reference/cli/spark/update",
                    "reference/cli/spark/verify-check",
                    "reference/cli/spark/verify-contract",
                  ],
                },
                {
                  type: "category",
                  label: "probe",
                  link: {
                    type: "doc",

                    id: "reference/cli/probe",
                  },
                  items: [
                    "reference/cli/probe/4byte",
                    "reference/cli/probe/4byte-decode",
                    "reference/cli/probe/4byte-event",
                    "reference/cli/probe/abi-decode",
                    "reference/cli/probe/abi-encode",
                    "reference/cli/probe/access-list",
                    "reference/cli/probe/address-zero",
                    "reference/cli/probe/admin",
                    "reference/cli/probe/age",
                    "reference/cli/probe/balance",
                    "reference/cli/probe/base-fee",
                    "reference/cli/probe/bind",
                    "reference/cli/probe/block",
                    "reference/cli/probe/block-number",
                    "reference/cli/probe/call",
                    "reference/cli/probe/call/--create",
                    "reference/cli/probe/calldata",
                    "reference/cli/probe/calldata-decode",
                    "reference/cli/probe/chain",
                    "reference/cli/probe/chain-id",
                    "reference/cli/probe/client",
                    "reference/cli/probe/code",
                    "reference/cli/probe/codesize",
                    "reference/cli/probe/completions",
                    "reference/cli/probe/compute-address",
                    "reference/cli/probe/concat-hex",
                    "reference/cli/probe/create2",
                    "reference/cli/probe/decode-transaction",
                    "reference/cli/probe/disassemble",
                    {
                      type: "category",
                      label: "probe estimate",
                      link: {
                        type: "doc",

                        id: "reference/cli/probe/estimate",
                      },
                      items: ["reference/cli/probe/estimate/--create"],
                    },
                    "reference/cli/probe/etherscan-source",
                    "reference/cli/probe/format-bytes32-string",
                    "reference/cli/probe/find-block",
                    "reference/cli/probe/from-bin",
                    "reference/cli/probe/from-fixed-point",
                    "reference/cli/probe/from-rlp",
                    "reference/cli/probe/from-utf8",
                    "reference/cli/probe/from-wei",
                    "reference/cli/probe/gas-price",
                    "reference/cli/probe/generate-fig-spec",
                    "reference/cli/probe/hash-zero",
                    "reference/cli/probe/implementation",
                    "reference/cli/probe/index",
                    "reference/cli/probe/interface",
                    "reference/cli/probe/keccak",
                    "reference/cli/probe/logs",
                    "reference/cli/probe/lookup-address",
                    "reference/cli/probe/max-int",
                    "reference/cli/probe/max-uint",
                    "reference/cli/probe/min-int",
                    "reference/cli/probe/namehash",
                    "reference/cli/probe/nonce",
                    "reference/cli/probe/parse-bytes32-address",
                    "reference/cli/probe/parse-bytes32-string",
                    "reference/cli/probe/pretty-calldata",
                    "reference/cli/probe/proof",
                    "reference/cli/probe/publish",
                    "reference/cli/probe/receipt",
                    "reference/cli/probe/resolve-name",
                    "reference/cli/probe/rpc",
                    "reference/cli/probe/run",
                    "reference/cli/probe/selectors",

                    {
                      type: "category",
                      label: "probe send",
                      link: {
                        type: "doc",

                        id: "reference/cli/probe/send",
                      },
                      items: ["reference/cli/probe/send/--create"],
                    },
                    "reference/cli/probe/shl",
                    "reference/cli/probe/shr",
                    "reference/cli/probe/sig",
                    "reference/cli/probe/sig-event",
                    "reference/cli/probe/storage",
                    "reference/cli/probe/to-ascii",
                    "reference/cli/probe/to-base",
                    "reference/cli/probe/to-bytes32",
                    "reference/cli/probe/to-check-sum-address",
                    "reference/cli/probe/to-dec",
                    "reference/cli/probe/to-fixed-point",
                    "reference/cli/probe/to-hex",
                    "reference/cli/probe/to-hexdata",
                    "reference/cli/probe/to-int256",
                    "reference/cli/probe/to-rlp",
                    "reference/cli/probe/to-uint256",
                    "reference/cli/probe/to-unit",
                    "reference/cli/probe/to-wei",
                    "reference/cli/probe/tx",
                    "reference/cli/probe/upload-signature",

                    {
                      type: "category",
                      label: "probe wallet",
                      link: {
                        type: "doc",

                        id: "reference/cli/probe/wallet",
                      },
                      items: [
                        "reference/cli/probe/wallet/new",
                        "reference/cli/probe/wallet/new-mnemonic",
                        "reference/cli/probe/wallet/vanity",
                        "reference/cli/probe/wallet/address",
                        "reference/cli/probe/wallet/sign",

                        "reference/cli/probe/wallet/verify",
                        "reference/cli/probe/wallet/import",
                        "reference/cli/probe/wallet/list",
                        "reference/cli/probe/wallet/derive-private-key",
                      ],
                    },
                  ],
                },
                {
                  type: "category",
                  label: "shuttle",
                  link: {
                    type: "doc",

                    id: "reference/cli/shuttle",
                  },
                  items: [
                    "reference/cli/shuttle/completions",
                    "reference/cli/shuttle/generate-fig-spec",
                  ],
                },
                {
                  type: "category",
                  label: "pilot",
                  link: {
                    type: "doc",

                    id: "reference/cli/pilot",
                  },
                  items: [
                    "reference/cli/pilot/list",
                    "reference/cli/pilot/load",
                    "reference/cli/pilot/view",
                    "reference/cli/pilot/clear-cache",
                  ],
                },
              ],
            },
            {
              type: "category",
              label: "Spark Commands",
              link: {
                type: "doc",

                id: "reference/spark/commands",
              },
              items: [
                {
                  type: "category",
                  label: "General Commands",
                  link: {
                    type: "doc",

                    id: "reference/spark/general-commands",
                  },
                  items: [
                    "reference/spark/spark",
                    "reference/spark/spark-help",
                    "reference/spark/spark-completions",
                  ],
                },
                {
                  type: "category",
                  label: "Project Commands",
                  link: {
                    type: "doc",

                    id: "reference/spark/project-commands",
                  },
                  items: [
                    "reference/spark/spark-init",
                    "reference/spark/spark-install",
                    "reference/spark/spark-update",
                    "reference/spark/spark-remove",
                    "reference/spark/spark-config",
                    "reference/spark/spark-remappings",
                    "reference/spark/spark-tree",
                    "reference/spark/spark-geiger",
                  ],
                },
                {
                  type: "category",
                  label: "Build Commands",
                  link: {
                    type: "doc",

                    id: "reference/spark/build-commands",
                  },
                  items: [
                    "reference/spark/spark-build",
                    "reference/spark/spark-clean",
                    "reference/spark/spark-inspect",
                  ],
                },
                {
                  type: "category",
                  label: "Test Commands",
                  link: {
                    type: "doc",

                    id: "reference/spark/test-commands",
                  },
                  items: [
                    "reference/spark/spark-test",
                    "reference/spark/spark-snapshot",
                    "reference/spark/spark-coverage",
                  ],
                },
                {
                  type: "category",
                  label: "Deploy Commands",
                  link: {
                    type: "doc",

                    id: "reference/spark/deploy-commands",
                  },
                  items: [
                    "reference/spark/spark-create",
                    "reference/spark/spark-verify-contract",
                    "reference/spark/spark-verify-check",
                    "reference/spark/spark-flatten",
                  ],
                },
                {
                  type: "category",
                  label: "Utility Commands",
                  link: {
                    type: "doc",

                    id: "reference/spark/utility-commands",
                  },
                  items: [
                    "reference/spark/spark-debug",
                    "reference/spark/spark-bind",
                    "reference/spark/spark-cache",
                    "reference/spark/spark-cache-clean",
                    "reference/spark/spark-cache-ls",
                    "reference/spark/spark-script",
                    "reference/spark/spark-upload-selectors",
                    "reference/spark/spark-doc",
                  ],
                },
              ],
            },
            {
              type: "category",
              label: "Probe Commands",
              link: {
                type: "doc",

                id: "reference/probe/probe-commands",
              },
              items: [
                {
                  type: "category",
                  label: "General Commands",
                  link: {
                    type: "doc",

                    id: "reference/probe/general-commands",
                  },
                  items: [
                    "reference/probe/probe",
                    "reference/probe/probe-help",
                    "reference/probe/probe-completions",
                  ],
                },
                {
                  type: "category",
                  label: "Chain Commands",
                  link: {
                    type: "doc",

                    id: "reference/probe/chain-commands",
                  },
                  items: [
                    "reference/probe/probe-chain-id",
                    "reference/probe/probe-chain",
                    "reference/probe/probe-client",
                  ],
                },
                {
                  type: "category",
                  label: "Transaction Commands",
                  link: {
                    type: "doc",

                    id: "reference/probe/transaction-commands",
                  },
                  items: [
                    "reference/probe/probe-publish",
                    "reference/probe/probe-receipt",
                    "reference/probe/probe-send",
                    "reference/probe/probe-call",
                    "reference/probe/probe-rpc",
                    "reference/probe/probe-tx",
                    "reference/probe/probe-run",
                    "reference/probe/probe-estimate",
                    "reference/probe/probe-access-list",
                    "reference/probe/probe-logs",
                  ],
                },
                {
                  type: "category",
                  label: "Block Commands",
                  link: {
                    type: "doc",

                    id: "reference/probe/block-commands",
                  },
                  items: [
                    "reference/probe/probe-find-block",
                    "reference/probe/probe-gas-price",
                    "reference/probe/probe-block-number",
                    "reference/probe/probe-basefee",
                    "reference/probe/probe-block",
                    "reference/probe/probe-age",
                  ],
                },
                {
                  type: "category",
                  label: "Account Commands",
                  link: {
                    type: "doc",

                    id: "reference/probe/account-commands",
                  },
                  items: [
                    "reference/probe/probe-balance",
                    "reference/probe/probe-storage",
                    "reference/probe/probe-proof",
                    "reference/probe/probe-nonce",
                    "reference/probe/probe-code",
                    "reference/probe/probe-codesize",
                  ],
                },
                {
                  type: "category",
                  label: "ENS Commands",
                  link: {
                    type: "doc",

                    id: "reference/probe/ens-commands",
                  },
                  items: [
                    "reference/probe/probe-lookup-address",
                    "reference/probe/probe-resolve-name",
                    "reference/probe/probe-namehash",
                  ],
                },
                {
                  type: "category",
                  label: "Etherscan Commands",
                  link: {
                    type: "doc",

                    id: "reference/probe/etherscan-commands",
                  },
                  items: ["reference/probe/probe-etherscan-source"],
                },
                {
                  type: "category",
                  label: "ABI Commands",
                  link: {
                    type: "doc",

                    id: "reference/probe/abi-commands",
                  },
                  items: [
                    "reference/probe/probe-abi-decode",
                    "reference/probe/probe-abi-encode",
                    "reference/probe/probe-4byte",
                    "reference/probe/probe-4byte-decode",
                    "reference/probe/probe-4byte-event",
                    "reference/probe/probe-calldata",
                    "reference/probe/probe-calldata-decode",
                    "reference/probe/probe-pretty-calldata",
                    "reference/probe/probe-selectors",
                    "reference/probe/probe-upload-signature",
                  ],
                },
                {
                  type: "category",
                  label: "Conversion Commands",
                  link: {
                    type: "doc",

                    id: "reference/probe/conversion-commands",
                  },
                  items: [
                    "reference/probe/probe-format-bytes32-string",
                    "reference/probe/probe-from-bin",
                    "reference/probe/probe-from-fixed-point",
                    "reference/probe/probe-from-rlp",
                    "reference/probe/probe-from-utf8",
                    "reference/probe/probe-from-wei",
                    "reference/probe/probe-parse-bytes32-address",
                    "reference/probe/probe-parse-bytes32-string",
                    "reference/probe/probe-to-ascii",
                    "reference/probe/probe-to-base",
                    "reference/probe/probe-to-bytes32",
                    "reference/probe/probe-to-dec",
                    "reference/probe/probe-to-fixed-point",
                    "reference/probe/probe-to-hex",
                    "reference/probe/probe-to-hexdata",
                    "reference/probe/probe-to-int256",
                    "reference/probe/probe-to-rlp",
                    "reference/probe/probe-to-uint256",
                    "reference/probe/probe-to-unit",
                    "reference/probe/probe-to-wei",
                    "reference/probe/probe-shl",
                    "reference/probe/probe-shr",
                  ],
                },
                {
                  type: "category",
                  label: "Utility Commands",
                  link: {
                    type: "doc",

                    id: "reference/probe/utility-commands",
                  },
                  items: [
                    "reference/probe/probe-sig",
                    "reference/probe/probe-sig-event",
                    "reference/probe/probe-keccak",
                    "reference/probe/probe-compute-address",
                    "reference/probe/probe-create2",
                    "reference/probe/probe-interface",
                    "reference/probe/probe-index",
                    "reference/probe/probe-concat-hex",
                    "reference/probe/probe-max-int",
                    "reference/probe/probe-min-int",
                    "reference/probe/probe-max-uint",
                    "reference/probe/probe-to-check-sum-address",
                  ],
                },
                {
                  type: "category",
                  label: "Wallet Commands",
                  link: {
                    type: "doc",

                    id: "reference/probe/wallet-commands",
                  },
                  items: [
                    "reference/probe/probe-wallet",
                    "reference/probe/probe-wallet-new",
                    "reference/probe/probe-wallet-new-mnemonic",
                    "reference/probe/probe-wallet-address",
                    "reference/probe/probe-wallet-sign",
                    "reference/probe/probe-wallet-vanity",
                    "reference/probe/probe-wallet-verify",
                    "reference/probe/probe-wallet-import",
                    "reference/probe/probe-wallet-list",
                  ],
                },
              ],
            },
            {
              type: "category",
              label: "Shuttle Reference",
              link: {
                type: "doc",

                id: "reference/shuttle/shuttle-reference",
              },
              items: [],
            },
            {
              type: "category",
              label: "Pilot Reference",
              link: {
                type: "doc",

                id: "reference/pilot/pilot-reference",
              },
              items: [],
            },
            {
              type: "category",
              label: "Config Reference",
              link: {
                type: "doc",

                id: "reference/config/config-reference",
              },
              items: [
                "reference/config/overview",
                "reference/config/project",
                "reference/config/solidity-compiler",
                "reference/config/testing",
                "reference/config/inline-test-config",
                "reference/config/formatter",
                "reference/config/doc-generator",
                "reference/config/etherscan",
              ],
            },
            {
              type: "category",
              label: "Cheatcodes Reference",
              link: {
                type: "doc",

                id: "reference/cheatcodes/cheatcodes-reference",
              },
              items: [
                {
                  type: "category",
                  label: "Environment",
                  link: {
                    type: "doc",

                    id: "reference/cheatcodes/environment",
                  },
                  items: [
                    "reference/cheatcodes/warp",
                    "reference/cheatcodes/roll",
                    "reference/cheatcodes/fee",
                    "reference/cheatcodes/get-block-timestamp",
                    "reference/cheatcodes/get-block-number",
                    "reference/cheatcodes/difficulty",
                    "reference/cheatcodes/prevrandao",
                    "reference/cheatcodes/chain-id",
                    "reference/cheatcodes/store",
                    "reference/cheatcodes/load",
                    "reference/cheatcodes/etch",
                    "reference/cheatcodes/deal",
                    "reference/cheatcodes/prank",
                    "reference/cheatcodes/start-prank",
                    "reference/cheatcodes/stop-prank",
                    "reference/cheatcodes/read-callers",
                    "reference/cheatcodes/record",
                    "reference/cheatcodes/accesses",
                    "reference/cheatcodes/prank",
                    "reference/cheatcodes/record-logs",
                    "reference/cheatcodes/get-recorded-logs",
                    "reference/cheatcodes/set-nonce",
                    "reference/cheatcodes/get-nonce",
                    "reference/cheatcodes/mock-call",
                    "reference/cheatcodes/mock-call-revert",
                    "reference/cheatcodes/clear-mocked-calls",
                    "reference/cheatcodes/coinbase",
                    "reference/cheatcodes/broadcast",
                    "reference/cheatcodes/start-broadcast",
                    "reference/cheatcodes/stop-broadcast",
                    "reference/cheatcodes/pause-gas-metering",
                    "reference/cheatcodes/resume-gas-metering",
                    "reference/cheatcodes/tx-gas-price",
                    "reference/cheatcodes/start-state",
                    "reference/cheatcodes/stop-and-return-state-diff",
                  ],
                },
                {
                  type: "category",
                  label: "Assertions",
                  link: {
                    type: "doc",

                    id: "reference/cheatcodes/assertions",
                  },
                  items: [
                    "reference/cheatcodes/expect-revert",
                    "reference/cheatcodes/expect-emit",
                    "reference/cheatcodes/expect-call",
                  ],
                },
                {
                  type: "category",
                  label: "Fuzzer",
                  link: {
                    type: "doc",

                    id: "reference/cheatcodes/fuzzer",
                  },
                  items: ["reference/cheatcodes/assume"],
                },
                {
                  type: "category",
                  label: "Forking",
                  link: {
                    type: "doc",

                    id: "reference/cheatcodes/forking",
                  },
                  items: [
                    "reference/cheatcodes/create-fork",
                    "reference/cheatcodes/select-fork",
                    "reference/cheatcodes/create-select-fork",
                    "reference/cheatcodes/active-fork",
                    "reference/cheatcodes/roll-fork",
                    "reference/cheatcodes/make-persistent",
                    "reference/cheatcodes/revoke-persistent",
                    "reference/cheatcodes/is-persistent",
                    "reference/cheatcodes/allow-cheatcodes",
                    "reference/cheatcodes/transact",
                  ],
                },
                {
                  type: "category",
                  label: "External",
                  link: {
                    type: "doc",

                    id: "reference/cheatcodes/external",
                  },
                  items: [
                    "reference/cheatcodes/ffi",
                    "reference/cheatcodes/project-root",
                    "reference/cheatcodes/get-code",
                    "reference/cheatcodes/get-deployed-code",
                    "reference/cheatcodes/sleep",
                    "reference/cheatcodes/unix-time",
                    "reference/cheatcodes/set-env",
                    "reference/cheatcodes/env-or",
                    "reference/cheatcodes/env-bool",
                    "reference/cheatcodes/env-uint",
                    "reference/cheatcodes/env-int",
                    "reference/cheatcodes/env-address",
                    "reference/cheatcodes/env-bytes32",
                    "reference/cheatcodes/env-string",
                    "reference/cheatcodes/env-bytes",
                    "reference/cheatcodes/parse-json",
                    "reference/cheatcodes/key-exists",
                    "reference/cheatcodes/parse-json-keys",
                    "reference/cheatcodes/serialize-json",
                    "reference/cheatcodes/write-json",
                  ],
                },
                {
                  type: "category",
                  label: "Utilities",
                  link: {
                    type: "doc",

                    id: "reference/cheatcodes/utilities",
                  },
                  items: [
                    "reference/cheatcodes/addr",
                    "reference/cheatcodes/sign",
                    "reference/cheatcodes/skip",
                    "reference/cheatcodes/label",
                    "reference/cheatcodes/get-label",
                    "reference/cheatcodes/derive-key",
                    "reference/cheatcodes/parse-bytes",
                    "reference/cheatcodes/parse-address",
                    "reference/cheatcodes/parse-uint",
                    "reference/cheatcodes/parse-int",
                    "reference/cheatcodes/parse-bytes32",
                    "reference/cheatcodes/parse-bool",
                    "reference/cheatcodes/remember-key",
                    "reference/cheatcodes/to-string",
                    "reference/cheatcodes/breakpoint",
                    "reference/cheatcodes/create-wallet",
                  ],
                },
                {
                  type: "category",
                  label: "Snapshots",
                  link: {
                    type: "doc",

                    id: "reference/cheatcodes/snapshots",
                  },
                  items: [],
                },
                {
                  type: "category",
                  label: "RPC",
                  link: {
                    type: "doc",

                    id: "reference/cheatcodes/rpc",
                  },
                  items: [],
                },
                {
                  type: "category",
                  label: "Files",
                  link: {
                    type: "doc",

                    id: "reference/cheatcodes/fs",
                  },
                  items: [],
                },
              ],
            },
            {
              type: "category",
              label: "Spark Standard Library Reference",
              link: {
                type: "doc",

                id: "reference/spark-std/spark-standart",
              },
              items: [
                "reference/spark-std/std-logs",
                {
                  type: "category",
                  label: "Std Assertions",
                  link: {
                    type: "doc",

                    id: "reference/spark-std/std-assertions",
                  },
                  items: [
                    "reference/spark-std/fail",
                    "reference/spark-std/assertFalse",
                    "reference/spark-std/assertEq",
                    "reference/spark-std/assertApproxEqAbs",
                    "reference/spark-std/assertApproxEqRel",
                  ],
                },
                {
                  type: "category",
                  label: "Std Cheats",
                  link: {
                    type: "doc",

                    id: "reference/spark-std/std-cheats",
                  },
                  items: [
                    "reference/spark-std/skip",
                    "reference/spark-std/rewind",
                    "reference/spark-std/hoax",
                    "reference/spark-std/startHoax",
                    "reference/spark-std/deal",
                    "reference/spark-std/deployCode",
                    "reference/spark-std/deployCodeTo",
                    "reference/spark-std/bound",
                    "reference/spark-std/change-prank",
                    "reference/spark-std/make-addr",
                    "reference/spark-std/make-addr-and-key",
                    "reference/spark-std/noGasMetering",
                    "reference/spark-std/assume-no-precompiles",
                    "reference/spark-std/assume-payable",
                  ],
                },
                {
                  type: "category",
                  label: "Std Errors",
                  link: {
                    type: "doc",

                    id: "reference/spark-std/std-errors",
                  },
                  items: [
                    "reference/spark-std/assertionError",
                    "reference/spark-std/arithmeticError",
                    "reference/spark-std/divisionError",
                    "reference/spark-std/enumConversionError",
                    "reference/spark-std/encodeStorageError",
                    "reference/spark-std/popError",
                    "reference/spark-std/indexOOBError",
                    "reference/spark-std/memOverflowError",
                    "reference/spark-std/zeroVarError",
                  ],
                },
                {
                  type: "category",
                  label: "Std Storage",
                  link: {
                    type: "doc",

                    id: "reference/spark-std/std-storage",
                  },
                  items: [
                    "reference/spark-std/target",
                    "reference/spark-std/sig",
                    "reference/spark-std/with_key",
                    "reference/spark-std/depth",
                    "reference/spark-std/checked_write",
                    "reference/spark-std/find",
                    "reference/spark-std/read",
                  ],
                },
                {
                  type: "category",
                  label: "Std Math",
                  link: {
                    type: "doc",

                    id: "reference/spark-std/std-math",
                  },
                  items: [
                    "reference/spark-std/abs",
                    "reference/spark-std/delta",
                    "reference/spark-std/percentDelta",
                  ],
                },
                {
                  type: "category",
                  label: "Script Utils",
                  link: {
                    type: "doc",

                    id: "reference/spark-std/script-utils",
                  },
                  items: [
                    "reference/spark-std/compute-create-address",
                    "reference/spark-std/derive-remember-key",
                  ],
                },
                {
                  type: "category",
                  label: "Console Logging",
                  link: {
                    type: "doc",

                    id: "reference/spark-std/console-log",
                  },
                  items: [],
                },
              ],
            },
            {
              type: "category",
              label: "DSTest Reference",
              link: {
                type: "doc",

                id: "reference/ds-test",
              },
              items: [],
            },
          ],
        },
        {
          type: "category",
          label: "Miscellaneous",
          link: {
            type: "doc",

            id: "misc/miscellaneous",
          },
          items: ["misc/struct-encoding", "misc/precompile-registry"],
        },
      ],
    },
  ],
};

export default sidebars;
