name: Docs linter
on:
  pull_request:
    branches:
      - master
    paths:
      - "docs/**/*.md"
      - "versioned_docs/**/*.md"
      - ".github/workflows/markdownlint.yml"
      - ".github/.markdownlint.json"

jobs:
  docs-linter:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3

      - name: Markdown Lint
        uses: ruzickap/action-my-markdown-linter@v1
        with:
          config_file: .github/lintconfig.yml
          search_paths: |
            docs/**/*.md
            versioned_docs/**/*.md
