name: Markdown Lint

on:
  push:
    paths:
      - "docs/**/*.md"
      - "versioned_docs/**/*.md"
  pull_request:
    paths:
      - "docs/**/*.md"
      - "versioned_docs/**/*.md"

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run markdownlint
        uses: ruzickap/action-my-markdown-linter@v1
        with:
          config_file: .github/.markdownlint.yml
          search_paths: |
            docs
            versioned_docs
